server.port=8761

eureka.instance.hostname= localhost

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone= http://${eureka.instance.hostname}:${server.port}/eureka/
eureka.client.eureka-service-url-poll-interval-seconds= 3000
